"""empty message

Revision ID: e308bff8ac35
Revises: 
Create Date: 2026-03-13 11:32:15.798556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e308bff8ac35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade models."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('ciphertext', sa.BINARY(), nullable=False),
    sa.Column('iv', sa.BINARY(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('blobs_user_updated_idx', 'blobs', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_blobs_user_id'), 'blobs', ['user_id'], unique=False)
    op.create_table('vaults',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wrapped_key', sa.BINARY(), nullable=False),
    sa.Column('iv', sa.BINARY(), nullable=False),
    sa.Column('salt', sa.BINARY(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade models."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaults')
    op.drop_index(op.f('ix_blobs_user_id'), table_name='blobs')
    op.drop_index('blobs_user_updated_idx', table_name='blobs')
    op.drop_table('blobs')
    op.drop_table('users')
    # ### end Alembic commands ###
